name: Release Tag


on:
  push:
    tags:
      - 'v*.*.*'       # root module tags
      - 'v*.*.*-*'     # pre-release tags
      
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - uses: goreleaser/goreleaser-action@v5
        with:
          version: '~> 2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}